# Generated by Django 6.0.6 on 2026-07-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_customer_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=15.0, help_text='Porcentaje de IVA aplicado a facturas y compras. Ej: 15.00 = 15%.', max_digits=5, verbose_name='IVA (%)')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
    ]
