# Generated by Django 6.0.6 on 2026-07-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='enviado_email',
            field=models.BooleanField(default=False, verbose_name='¿Enviada por correo?'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fecha_envio_email',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío por correo'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('PAYPAL', 'PayPal')], help_text='Cómo se pagó la factura de contado. No aplica a facturas a crédito.', max_length=15, null=True, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paypal_capture_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de captura PayPal'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de orden PayPal'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paypal_payer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del pagador (PayPal)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paypal_status',
            field=models.CharField(blank=True, choices=[('CREATED', 'Creada'), ('APPROVED', 'Aprobada'), ('COMPLETED', 'Completada'), ('FAILED', 'Fallida')], max_length=15, null=True, verbose_name='Estado PayPal'),
        ),
    ]
