# Generated by Django 6.0.6 on 2026-07-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_invoice_enviado_email_invoice_fecha_envio_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'permissions': [('exportar_pdf_brand', 'Puede exportar Marcas a PDF'), ('exportar_excel_brand', 'Puede exportar Marcas a Excel')], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('exportar_pdf_customer', 'Puede exportar Clientes a PDF'), ('exportar_excel_customer', 'Puede exportar Clientes a Excel')]},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date'], 'permissions': [('exportar_pdf_invoice', 'Puede exportar Facturas a PDF'), ('exportar_excel_invoice', 'Puede exportar Facturas a Excel')]},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('exportar_pdf_product', 'Puede exportar Productos a PDF'), ('exportar_excel_product', 'Puede exportar Productos a Excel')], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ['name'], 'permissions': [('exportar_pdf_productgroup', 'Puede exportar Grupos de Productos a PDF'), ('exportar_excel_productgroup', 'Puede exportar Grupos de Productos a Excel')], 'verbose_name': 'Product Group', 'verbose_name_plural': 'Product Groups'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'permissions': [('exportar_pdf_supplier', 'Puede exportar Proveedores a PDF'), ('exportar_excel_supplier', 'Puede exportar Proveedores a Excel')], 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
    ]
