# Generated by Django 6.0.6 on 2026-07-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_brand_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date'], 'permissions': [('exportar_pdf_invoice', 'Puede exportar Facturas a PDF'), ('exportar_excel_invoice', 'Puede exportar Facturas a Excel'), ('imprimir_factura', 'Puede imprimir el documento de la factura')]},
        ),
    ]
