# Generated by Django 6.0.6 on 2026-07-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_alter_invoice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date'], 'permissions': [('exportar_pdf_invoice', 'Puede exportar Facturas a PDF'), ('exportar_excel_invoice', 'Puede exportar Facturas a Excel'), ('imprimir_factura', 'Puede imprimir el documento de la factura'), ('cancelar_invoice_paypal', 'Puede cancelar facturas PayPal pendientes')]},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PAGADA', 'PAGADA'), ('CANCELADA', 'CANCELADA')], default='PENDIENTE', max_length=15),
        ),
    ]
