# Generated by Django 6.0.6 on 2026-07-16 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_alter_invoice_options_alter_invoice_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Porcentaje de IVA aplicado a facturas y compras. Ej: 15.00 = 15%.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='IVA (%)'),
        ),
    ]
