# Generated by Django 6.0.6 on 2026-07-17 03:58

import django.core.validators
from django.conf import settings
from django.db import migrations, models


def backfill_desde_settings(apps, schema_editor):
    """
    RUC/dirección/teléfono ya vivían como EMPRESA_RUC/EMPRESA_DIRECCION/
    EMPRESA_TELEFONO en settings.py (.env) antes de esta migración. Si están
    configurados ahí, se copian al registro singleton para que un deploy
    existente (ej. Railway) no pierda el dato que ya tenía -- razón_social/
    nombre_comercial/dirección_establecimiento/código/punto_emisión son
    campos nuevos sin equivalente previo, quedan vacíos hasta que se
    completen desde la UI.
    """
    ConfiguracionSistema = apps.get_model('billing', 'ConfiguracionSistema')
    ruc = getattr(settings, 'EMPRESA_RUC', '')
    direccion = getattr(settings, 'EMPRESA_DIRECCION', '')
    telefono = getattr(settings, 'EMPRESA_TELEFONO', '')
    if not (ruc or direccion or telefono):
        return
    config, _ = ConfiguracionSistema.objects.get_or_create(pk=1, defaults={'iva_porcentaje': 15.00})
    if ruc:
        config.ruc = ruc
    if direccion:
        config.direccion_matriz = direccion
    if telefono:
        config.telefono = telefono
    config.save()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_alter_configuracionsistema_iva_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='codigo_establecimiento',
            field=models.CharField(blank=True, default='', max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'Debe tener 3 dígitos numéricos (ej: 001).')], verbose_name='Código de Establecimiento'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='direccion_establecimiento',
            field=models.CharField(blank=True, default='', help_text='Opcional -- si se deja vacío, se usa la dirección matriz.', max_length=255, verbose_name='Dirección del Establecimiento'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='direccion_matriz',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección Matriz'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='nombre_comercial',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre Comercial'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='punto_emision',
            field=models.CharField(blank=True, default='', max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'Debe tener 3 dígitos numéricos (ej: 001).')], verbose_name='Punto de Emisión'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='razon_social',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='ruc',
            field=models.CharField(blank=True, default='', max_length=13, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'El RUC debe tener 13 dígitos numéricos.')], verbose_name='RUC'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono'),
        ),
        migrations.RunPython(backfill_desde_settings, migrations.RunPython.noop),
    ]
