# Generated by Django 6.0.6 on 2026-07-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditos_compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuotacompra',
            options={'ordering': ['compra', 'numero'], 'permissions': [('imprimir_plan_pagos', 'Puede imprimir el plan de pagos')]},
        ),
    ]
