# Generated by Django 6.0.6 on 2026-07-16 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDefaultPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_permissions', to='auth.group')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
            options={
                'verbose_name': 'Permisos predeterminados de rol',
                'verbose_name_plural': 'Permisos predeterminados de roles',
            },
        ),
    ]
