"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import urllib.parse
from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-CAMBIA-ESTO-EN-TU-.env')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=lambda v: [s.strip() for s in v.split(',') if s.strip()]) or ['*']
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='https://*.railway.app', cast=lambda v: [s.strip() for s in v.split(',') if s.strip()])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # apps users
    'billing',
    'purchasing',
    'security',
    'creditos_ventas',
    'creditos_compras',
    'widget_tweaks',
    'django_extensions',
    'anymail',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'shared.middleware.ForcePasswordChangeMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_db_url = config('DATABASE_URL', default='')
if _db_url:
    _u = urllib.parse.urlparse(_db_url)
    DATABASES = {
        'default': {
            'ENGINE':   'django.db.backends.postgresql',
            'NAME':     _u.path.lstrip('/'),
            'USER':     _u.username or '',
            'PASSWORD': _u.password or '',
            'HOST':     _u.hostname or 'localhost',
            'PORT':     str(_u.port or 5432),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE':   'django.db.backends.postgresql',
            'NAME':     config('DB_NAME'),
            'USER':     config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST':     config('DB_HOST', default='localhost'),
            'PORT':     config('DB_PORT', default='5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
LOGIN_URL = '/accounts/login/'


# ── Correo (Gmail SMTP) ──────────────────────────────────────────────────
# Las credenciales YA NO viven aquí en texto plano: se leen del archivo
# .env (que no se sube a git). Mira .env.example para saber qué variables
# crear y cómo generar la "Contraseña de aplicación" en Gmail.
EMAIL_BACKEND = config(
    'EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend'
)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='')

ANYMAIL = {
    'SENDGRID_API_KEY': config('SENDGRID_API_KEY', default=''),
}

# Nota: por defecto EMAIL_BACKEND queda en 'console' (imprime el correo en
# la terminal en vez de enviarlo), así el proyecto sigue corriendo aunque
# no hayas configurado el .env todavía. En cuanto pongas EMAIL_HOST_USER /
# EMAIL_HOST_PASSWORD reales en tu .env, cambia también EMAIL_BACKEND=
# django.core.mail.backends.smtp.EmailBackend ahí mismo.


# ── PayPal (Checkout API v2 - sandbox) ───────────────────────────────────
PAYPAL_CLIENT_ID = config('PAYPAL_CLIENT_ID', default='')
PAYPAL_CLIENT_SECRET = config('PAYPAL_CLIENT_SECRET', default='')
PAYPAL_MODE = config('PAYPAL_MODE', default='sandbox')  # 'sandbox' o 'live'

# Microservicio SRI — dejar SRI_MICRO_URL vacío para desactivar
SRI_MICRO_URL     = config('SRI_MICRO_URL', default='')
SRI_MICRO_API_KEY = config('SRI_MICRO_API_KEY', default='')
SRI_MICRO_TIMEOUT = config('SRI_MICRO_TIMEOUT', default=30, cast=int)
SRI_STORE_NAME    = config('SRI_STORE_NAME', default='')
SRI_LOGO_URL      = config('SRI_LOGO_URL', default='')

# DEPRECADO -- la identidad tributaria del negocio se movió a
# ConfiguracionSistema (editable desde Configuración del Sistema en la UI).
# Nada en el código lee esto ya (billing/invoice_pdf.py usa
# ConfiguracionSistema.get_activa()); se dejan estas 3 líneas SOLO para que
# la migración billing/migrations/0015_identidad_tributaria.py pueda
# copiar el valor que ya estaba configurado en Railway hacia la base de
# datos en el próximo deploy. Una vez confirmado que esa migración corrió
# en producción, borrar estas 3 líneas y las variables EMPRESA_* de Railway.
EMPRESA_RUC        = config('EMPRESA_RUC', default='')
EMPRESA_DIRECCION  = config('EMPRESA_DIRECCION', default='')
EMPRESA_TELEFONO   = config('EMPRESA_TELEFONO', default='')