# Generated by Django 6.0.6 on 2026-07-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_purchase_estado_purchase_saldo_purchase_tipo_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date'], 'permissions': [('exportar_pdf_purchase', 'Puede exportar Compras a PDF'), ('exportar_excel_purchase', 'Puede exportar Compras a Excel')], 'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
    ]
