# Generated by Django 6.0.6 on 2026-07-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_alter_purchase_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date'], 'permissions': [('exportar_pdf_purchase', 'Puede exportar Compras a PDF'), ('exportar_excel_purchase', 'Puede exportar Compras a Excel'), ('view_purchase_report', 'Puede ver el reporte de compras')], 'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
    ]
