# Generated by Django 6.0.6 on 2026-07-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos_ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocuotaventa',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('PAYPAL', 'PayPal')], max_length=15, null=True, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='pagocuotaventa',
            name='paypal_capture_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de captura PayPal'),
        ),
        migrations.AddField(
            model_name='pagocuotaventa',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID de orden PayPal'),
        ),
        migrations.AddField(
            model_name='pagocuotaventa',
            name='paypal_payer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del pagador (PayPal)'),
        ),
        migrations.AddField(
            model_name='pagocuotaventa',
            name='paypal_status',
            field=models.CharField(blank=True, choices=[('CREATED', 'Creada'), ('APPROVED', 'Aprobada'), ('COMPLETED', 'Completada'), ('FAILED', 'Fallida')], max_length=15, null=True, verbose_name='Estado PayPal'),
        ),
    ]
