# Generated by Django 6.0.6 on 2026-07-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditos_ventas', '0002_pagocuotaventa_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuotaventa',
            options={'ordering': ['factura', 'numero'], 'permissions': [('imprimir_plan_pagos', 'Puede imprimir el plan de pagos')]},
        ),
    ]
